### ISSUE TITLE
bit test failed

### ISSUE THREAD

**Issue by SenthilkumarJ** [teambit/bit-lit#6]
Upgraded bit version to 0.0.493 and updated the Lit environment version to 0.0.8, getting an error

PS C:\Bit\purchase-cart> bit test
√ teambit.component/isolator, create capsules network (completed in 241ms)
testing total of 2 components in workspace 'purchase-cart'
testing 1 components with environment teambit.web-components/lit@0.0.8
 FAIL  purchase-mfe/basket-summary/src/basket-summary-component.test.ts
  ● Test suite failed to run
    Jest encountered an unexpected token
    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.
    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".
    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/en/ecmascript-modules for how to enable it.
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.
    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html
    Details:
    C:\Bit\purchase-cart\node_modules\.pnpm\@open-wc\testing-helpers@1.8.12\node_modules\@open-wc\testing-helpers\index.js:1
    ({"Object.<anonymous>":function(module,exports,require,_dirname,_filename,global,jest){export { elementUpdated } from './src/elementUpdated.js';
                                                                                             ^^^^^^
    SyntaxError: Unexpected token 'export'
    > 1 | import {fixture, fixtureCleanup} from '@open-wc/testing-helpers';
        | ^
      2 | import {html} from 'lit-element';
      3 | import {BasketSummaryComponent} from './components/basket-summary/basket-summary-component';
      4 | import sinon, {SinonSandbox} from 'sinon';
      at Runtime.createScriptFromCode (../../Users/Senthilkumar_J/AppData/Local/.bvm/versions/0.0.493/bit-0.0.493/node_modules/jest-runtime/build/index.js:1350:14)
      at Object.<anonymous> (purchase-mfe/basket-summary/src/basket-summary-component.test.ts:1:1)
Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        9.711 s
Ran all test suites.
tested 2 components in 16.655 seconds.

**Comment by GiladShoham** [comment]
It looks like the pnpm structure is different.
I have something like this
`D:\dev\bit-lit\node_modules\.pnpm\registry.npmjs.org\lit@2.0.0-rc.3\node_modules\lit\index.js:1`
while in your case it's:
`C:\Bit\purchase-cart\node_modules.pnpm@open-wc\testing-helpers@1.8.12\node_modules@open-wc\testing-helpers\index.js:1`

The [current regex](https://github.com/teambit/bit-lit/blob/main/web-components/lit/jest/jest.config.js#L21) expect my structure. 
I'll fix it

**Comment by GiladShoham** [comment]
solved on v0.0.9
